### ISSUE TITLE
deployed via docker-compose but I probably miss something

### ISSUE THREAD

**Issue by aracloud** [tomsajan/netio-exporter#6]
docker logs netio-exporter-apupi

shows following....

INFO:netio-exporter:Starting Netio Prometheus Exporter
DEBUG:netio-exporter:Scraping netio at http://netio/netio.json
DEBUG:netio-exporter:Processing netio agent info
DEBUG:netio-exporter:Agent info metric: Metric(netio_agent, Global info about Netio agent, info, , [Sample(name='netio_agent_info', labels={'model': 'NETIO 4C', 'version': '3.4.3', 'json_version': '2.1', 'name': 'pdu', 'outputs': '4', 'sn': 'serialnumber', 'target': 'http://netio/netio.json'}, value=1, timestamp=None, exemplar=None)])
DEBUG:netio-exporter:Processing global stats
DEBUG:netio-exporter:Processing individual Netio outputs.
**DEBUG:netio-exporter:Output metric "ID" not processed. Either not known or not wanted
DEBUG:netio-exporter:Output metric "Name" not processed. Either not known or not wanted
DEBUG:netio-exporter:Processing "State" output metric.
DEBUG:netio-exporter:Output metric "Action" not processed. Either not known or not wanted
DEBUG:netio-exporter:Output metric "Delay" not processed. Either not known or not wanted**

compose snip:
```
  netio-exporter:
    image: tomsajan/netio-exporter:latest
    container_name: netio-exporter-apupi
    ports:
      - 9595:9595
    restart: always
    environment:
      - NETIO_DEBUG=true
      - NETIO_URL=http://<ip>/netio.json
      - NETIO_USERNAME=test
      - NETIO_PASSWORD=test
```
Prometheus.yml config:

```
  - job_name: netio-exporter
    static_configs:
      - targets: ['<dockerhost>:9595']
```

did I miss something? 

Thank you for your reply!

:-)
